---
title: "projet S7"
author: "Sahi Gonsangbeu"
date: "29/01/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Simulation processus de Poisson homogène

Pour simuler un processus de Poisson homogène de paramètre $\lambda$, on génère un vecteur de variables aléatoires indépendantes de loi exponentielle de paramètre $\lambda$. Il s'agit des vecteurs des inter-arrivées $(T_n)_{n \geq 1}$ puis on génère le vecteur des occurrences $(t_k)_{k \geq 1}$ par la formule :

$$
t_1 = T_1 \\
t_k = t_{k-1} + T_k,   \forall k > 1
$$


```{r}
# Simulation en fonction du nombre d'évènements
simul_poisson <- function(n, lambda) {
  T <- cumsum(rexp(n, lambda))
  t <- c(0, T)
  return(t)
}
```

```{r}
# Simulation jusqu'à une date T

simul_poisson2 <- function(T, lambda) {
  i <- 2
  t <- 0
  while (t[length(t)] < T) {
    w <- rexp(1, lambda)
    t[i] <- t[i - 1] + w
    i <- i + 1
  }
  return(t)
}
```

```{r}
lambda <- 5
T <- 50
t <- simul_poisson2(T, lambda)
t1 <- simul_poisson2(100, 10)
n1 <- length(t1) - 1
n <- length(t) - 1
N <- c(0:n)
N1 <- c(0:n1)
plot(t, N, type = "s", ylab = "N(t)")
lines(t1, N1, type = "s", ylab = "N(t)", col = "red")
```
```{r}
t <- simul_poisson2(5, 1)
ks.test(t, "pexp")
```

