name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.2"
      - name: Install dependencies
        run: |
          R -e 'install.packages("lintr")'
      - name: Lint
        run: |
          R -e 'lintr::lint_package()'
      - name: Run
        run: |
          Rscript -e 'tests_stats_on_data.R'
